### ISSUE TITLE
can not open db file

### ISSUE THREAD

**Issue by yanngxinlei** [GIKICoder/GDataBase#3]
在5s 的机型上，使用报错，系统10.3.2，Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'can not open db file'

**Comment by GIKICoder** [comment]
FMDB Can not open db.

**Comment by L-vinCent** [comment]
the directories path is wrong ，use stringByAppendingPathComponent replace  stringByAppendingString

**Comment by GIKICoder** [comment]
Fix~~
