### ISSUE TITLE
获取模型属性报错

### ISSUE THREAD

**Issue by yanngxinlei** [GIKICoder/GDataBase#5]
<img width="964" alt="WeChat3c9e4f2ea9f41f4618558c2a3dbf4b55" src="https://user-images.githubusercontent.com/13198051/58761451-0bf94a00-8577-11e9-84b2-7bfbd86cac5e.png">

**Comment by GIKICoder** [comment]
GDATABASE_IMPLEMENTATION_INJECT(xccclass) orm模型中需要加上这句注入语句。
